//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software2
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminder
    {
        public int reminderId { get; set; }
        public System.DateTime reminderDate { get; set; }
        public int snoozeIncrement { get; set; }
        public int snoozeIncrementTypeId { get; set; }
        public int appointmentId { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string remindercol { get; set; }
    }
}
